[package]
name = "hydrochess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.3"

[dependencies]
lazy_static = "1.4.0"
rand = "0.8.5"
rand_chacha = "0.3.1"